unique_ids:
  assets:
    standard-page.html: PRD7RKQ3FRM5BT4AX22DYRDGTADUA43U
    theme.css: TDGRV6TOWEHWLV3JWLHCLURQUP4JW2IH
  forms:
    Form1: DQ2WTWMH7ZLI5Q7AMVWW5CMSGETYJYYW
  modules: {}
  scripts: {}
  server_modules: {}
